# Generated by Django 6.1 on 2026-08-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_date_of_birth_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.student')),
            ],
        ),
    ]
