# Generated by Django 6.1 on 2026-08-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Student',
            new_name='student',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_cart'),
        ),
    ]
