# Generated by Django 6.1 on 2026-10-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('video', 'Video Lesson'), ('document', 'Document / PDF'), ('article', 'Reading / Article'), ('quiz', 'Quiz / Exercise'), ('assignment', 'Assignment'), ('other', 'Other')], default='video', max_length=30)),
                ('video_url', models.URLField(blank=True, help_text='Link to lecture video (YouTube, Vimeo, or external stream)', max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, help_text='Link to study material, PDF, or resource', max_length=500, null=True)),
                ('text_content', models.TextField(blank=True, help_text='Lesson notes, article text, or lecture transcript', null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in course syllabus')),
                ('duration', models.CharField(blank=True, help_text='Estimated duration (e.g. 15 mins)', max_length=50, null=True)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Whether this content is visible before purchasing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Content',
                'verbose_name_plural': 'Course Contents',
                'ordering': ['order', 'content_id'],
            },
        ),
    ]
